/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./scene.gltf 
Author: hipoojan (https://sketchfab.com/hipoojan)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/canyon-aeroad-road-bike-bf3133aacf9043b287525aa9d47cbacc
Title: Canyon Aeroad | Road Bike
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function BikeModel(props) {
  const { scene } = useGLTF('/models/Bike/scene.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.111}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes._rootJoint} />
            <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.Canyon} skeleton={nodes.Object_7.skeleton} />
            <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.Canyon} skeleton={nodes.Object_8.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
